// <auto-generated />
using System;
using CartSchedule.Api.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CartSchedule.Api.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CartSchedule.Api.Domain.Carrinho", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("carrinhos", (string)null);
                });

            modelBuilder.Entity("CartSchedule.Api.Domain.CarrinhoTurno", b =>
                {
                    b.Property<int>("CarrinhoId")
                        .HasColumnType("integer");

                    b.Property<int>("TurnoId")
                        .HasColumnType("integer");

                    b.HasKey("CarrinhoId", "TurnoId");

                    b.HasIndex("TurnoId");

                    b.ToTable("carrinho_turnos", (string)null);
                });

            modelBuilder.Entity("CartSchedule.Api.Domain.Escala", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("MesReferencia")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("MesReferencia")
                        .IsUnique();

                    b.ToTable("escalas", (string)null);
                });

            modelBuilder.Entity("CartSchedule.Api.Domain.Publicador", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("publicadores", (string)null);
                });

            modelBuilder.Entity("CartSchedule.Api.Domain.Solicitacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CarrinhoId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DecididoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DiaSemana")
                        .HasColumnType("integer");

                    b.Property<int>("EscalaId")
                        .HasColumnType("integer");

                    b.Property<int>("Origem")
                        .HasColumnType("integer");

                    b.Property<Guid>("PublicadorId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("TurnoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CarrinhoId");

                    b.HasIndex("TurnoId");

                    b.HasIndex("EscalaId", "CarrinhoId", "DiaSemana", "TurnoId");

                    b.HasIndex("PublicadorId", "EscalaId", "CarrinhoId", "DiaSemana", "TurnoId")
                        .IsUnique();

                    b.ToTable("solicitacoes", (string)null);
                });

            modelBuilder.Entity("CartSchedule.Api.Domain.Turno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<TimeOnly>("HoraFim")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasColumnType("time without time zone");

                    b.HasKey("Id");

                    b.ToTable("turnos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HoraFim = new TimeOnly(8, 0, 0),
                            HoraInicio = new TimeOnly(6, 0, 0)
                        },
                        new
                        {
                            Id = 2,
                            HoraFim = new TimeOnly(10, 0, 0),
                            HoraInicio = new TimeOnly(8, 0, 0)
                        },
                        new
                        {
                            Id = 3,
                            HoraFim = new TimeOnly(12, 0, 0),
                            HoraInicio = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = 4,
                            HoraFim = new TimeOnly(16, 0, 0),
                            HoraInicio = new TimeOnly(14, 0, 0)
                        },
                        new
                        {
                            Id = 5,
                            HoraFim = new TimeOnly(18, 0, 0),
                            HoraInicio = new TimeOnly(16, 0, 0)
                        },
                        new
                        {
                            Id = 6,
                            HoraFim = new TimeOnly(20, 0, 0),
                            HoraInicio = new TimeOnly(18, 0, 0)
                        });
                });

            modelBuilder.Entity("CartSchedule.Api.Domain.CarrinhoTurno", b =>
                {
                    b.HasOne("CartSchedule.Api.Domain.Carrinho", "Carrinho")
                        .WithMany("CarrinhoTurnos")
                        .HasForeignKey("CarrinhoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CartSchedule.Api.Domain.Turno", "Turno")
                        .WithMany("CarrinhoTurnos")
                        .HasForeignKey("TurnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carrinho");

                    b.Navigation("Turno");
                });

            modelBuilder.Entity("CartSchedule.Api.Domain.Solicitacao", b =>
                {
                    b.HasOne("CartSchedule.Api.Domain.Carrinho", "Carrinho")
                        .WithMany("Solicitacoes")
                        .HasForeignKey("CarrinhoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CartSchedule.Api.Domain.Escala", "Escala")
                        .WithMany("Solicitacoes")
                        .HasForeignKey("EscalaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CartSchedule.Api.Domain.Publicador", "Publicador")
                        .WithMany("Solicitacoes")
                        .HasForeignKey("PublicadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CartSchedule.Api.Domain.Turno", "Turno")
                        .WithMany("Solicitacoes")
                        .HasForeignKey("TurnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carrinho");

                    b.Navigation("Escala");

                    b.Navigation("Publicador");

                    b.Navigation("Turno");
                });

            modelBuilder.Entity("CartSchedule.Api.Domain.Carrinho", b =>
                {
                    b.Navigation("CarrinhoTurnos");

                    b.Navigation("Solicitacoes");
                });

            modelBuilder.Entity("CartSchedule.Api.Domain.Escala", b =>
                {
                    b.Navigation("Solicitacoes");
                });

            modelBuilder.Entity("CartSchedule.Api.Domain.Publicador", b =>
                {
                    b.Navigation("Solicitacoes");
                });

            modelBuilder.Entity("CartSchedule.Api.Domain.Turno", b =>
                {
                    b.Navigation("CarrinhoTurnos");

                    b.Navigation("Solicitacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
